### ISSUE TITLE
How to use pseudotime from prediction?

### ISSUE THREAD

**Issue by duocang** [KChen-lab/cyclum#4]
Hi.

I have a question about the prediction. The pseudotime includes continuous values:
![image](https://user-images.githubusercontent.com/14146871/112861417-0f978280-90b5-11eb-893a-8c4e8f3ab36d.png)

How can get cell cycle information from pseudotime? For example, the pseudotime value  for `cell 1` is 1.8102. Which cycle of `cell 1` is it?

**Comment by lshh125** [comment]
Unfortunately, we didn't include a way to identify the specific cell cycle phase in the package at this moment. 

However, you can conveniently use "scanpy.tl.score_genes_cell_cycle" in SCANPY (https://scanpy.readthedocs.io/en/stable/api/scanpy.tl.score_genes_cell_cycle.html) to do assign cell cycle scores to cells. Seurat also has similar functionalities (https://satijalab.org/seurat/archive/v3.1/cell_cycle_vignette.html). Plotting those scores ~ pseudotime will give you a better view. You can use it to find the interval of pseudotime where cells are scored highly for G2/S or G1/M.

This might seem a bit redundant, but remember that Cyclum uses more information than the scores and is more robust to noise. The key idea of Cyclum is to (1) give a continuous embedding of cells (instead of discrete phases) through the cell cycle, and (2) potentially an ab initio view of the process without being biased by the gene sets. On the other hand, without knowing the gene sets it cannot name the phases.

**Comment by lshh125** [comment]
We added a new functionality (https://github.com/KChen-lab/Cyclum#refine-labels-from-other-sources) which might be helpful to you. It might not be exactly what was requested but once you have labels from Scanpy or Seurat, you can use Cyclum to refine it using the inferred pseudotime now. 

Thank you for your interest and hope it helps to some extent.
